#!/bin/bash

# Interactive setup script for Azure Logic App and Function App deployment

set -e

echo "==================================="
echo "Azure List Processing Apps Setup"
echo "==================================="
echo

# Check for Azure CLI
if ! command -v az &> /dev/null; then
    echo "Error: Azure CLI is not installed."
    echo "Please install it from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if logged in
if ! az account show &> /dev/null; then
    echo "Please log in to Azure..."
    az login
fi

# Create config file if it doesn't exist
CONFIG_FILE="$(dirname "$0")/config.env"
if [ ! -f "$CONFIG_FILE" ]; then
    cp "$(dirname "$0")/config.env.template" "$CONFIG_FILE"
fi

# Function to prompt with validation
prompt_with_validation() {
    local var_name=$1
    local prompt=$2
    local pattern=$3
    local error_msg=$4
    local default=$5

    while true; do
        if [ -n "$default" ]; then
            read -p "$prompt [$default]: " value
            value=${value:-$default}
        else
            read -p "$prompt: " value
        fi

        if [[ $value =~ $pattern ]]; then
            eval "$var_name='$value'"
            break
        else
            echo "Error: $error_msg"
        fi
    done
}

echo "Please provide the following configuration values:"
echo "(Press Enter to use default values where shown)"
echo

# Resource Group
prompt_with_validation RESOURCE_GROUP \
    "Resource Group name" \
    "^[a-zA-Z0-9._-]{1,90}$" \
    "1-90 characters, alphanumeric, underscores, hyphens, periods only"

# Function App Name
prompt_with_validation FUNC_APP_NAME \
    "Function App name" \
    "^[a-zA-Z0-9-]{2,60}$" \
    "2-60 characters, alphanumeric and hyphens only"

# Logic App Name
prompt_with_validation LOGIC_APP_NAME \
    "Logic App name" \
    "^[a-zA-Z0-9._-]{1,80}$" \
    "1-80 characters, alphanumeric, hyphens, underscores, periods only"

# Location
prompt_with_validation LOCATION \
    "Azure region" \
    "^[a-z0-9]+$" \
    "Invalid region format" \
    "eastus"

# Storage Account (auto-generate based on function app name)
default_storage=$(echo "${FUNC_APP_NAME}store" | tr -d '-' | tr '[:upper:]' '[:lower:]' | cut -c1-24)
prompt_with_validation STORAGE_ACCOUNT \
    "Storage account name" \
    "^[a-z0-9]{3,24}$" \
    "3-24 characters, lowercase letters and numbers only" \
    "$default_storage"

# App Insights
default_insights="${FUNC_APP_NAME}-insights"
prompt_with_validation APP_INSIGHTS_NAME \
    "Application Insights name" \
    "^[a-zA-Z0-9-_.()]{1,255}$" \
    "Invalid name format" \
    "$default_insights"

# Report Email
prompt_with_validation REPORT_EMAIL \
    "Report email address" \
    "^[^@]+@[^@]+\.[^@]+$" \
    "Invalid email format"

# Admin Email
prompt_with_validation ADMIN_EMAIL \
    "Admin email address" \
    "^[^@]+@[^@]+\.[^@]+$" \
    "Invalid email format"

# Watched Folders
read -p "Watched folders (comma-separated) [Inbox,Bounces]: " WATCHED_FOLDERS
WATCHED_FOLDERS=${WATCHED_FOLDERS:-"Inbox,Bounces"}

# Save configuration
cat > "$CONFIG_FILE" << EOF
# Azure Deployment Configuration
# Generated by setup.sh on $(date)

RESOURCE_GROUP=$RESOURCE_GROUP
FUNC_APP_NAME=$FUNC_APP_NAME
LOGIC_APP_NAME=$LOGIC_APP_NAME
LOCATION=$LOCATION
STORAGE_ACCOUNT=$STORAGE_ACCOUNT
APP_INSIGHTS_NAME=$APP_INSIGHTS_NAME
REPORT_EMAIL=$REPORT_EMAIL
ADMIN_EMAIL=$ADMIN_EMAIL
WATCHED_FOLDERS=$WATCHED_FOLDERS
EOF

echo
echo "Configuration saved to $CONFIG_FILE"
echo
echo "To deploy, run: ./scripts/deploy.sh"
echo
